name: "DB-prepare"
description: "Prepare wordpress databases"
author: "Hugo Hammarström"
branding:
  icon: database
  color: orange
inputs:
  config_path:
    description: "Path to config file to use"
    default: "db-prepare-config.yaml"
  ssh_host:
    description: "Host to export db from"
    default: ""
  ssh_user:
    description: "Host to export db from"
    default: ""
  installation_path:
    description: "Path on host where wordpress is installed"
    default: "/var/www/html"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.config_path }}
    - ${{ inputs.ssh_host }}
    - ${{ inputs.ssh_user }}
    - ${{ inputs.installation_path }}
