version: 1
dumpfile: db.sql
output_file: db/newsner-dev-{date}-{time}-localhost.sql
no_export: true
sites:
  - steps:
      - search: https://newsner-do.newsnerdev.com
        replace: http://newsner-do.newsner.localhost
      - search: http://newsner-do.newsnerdev.com
        replace: http://newsner-do.newsner.localhost
      - search: newsner-do.newsnerdev.com
        replace: newsner-do.newsner.localhost
